"""Init

Revision ID: 943c3baadbb6
Revises: 
Create Date: 2025-01-10 22:59:11.684740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943c3baadbb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_state',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thread_id', sa.BIGINT(), nullable=True),
    sa.Column('business_connection_id', sa.VARCHAR(), nullable=True),
    sa.Column('destiny', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    # ### end Alembic commands ###
